apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rewritingyesterdaytoday-com-tls
spec:
  secretName: rewritingyesterdaytoday-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rewritingyesterdaytoday.com
  dnsNames:
    - rewritingyesterdaytoday.com
    - www.rewritingyesterdaytoday.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rewritingyesterdaytoday.com
          - www.rewritingyesterdaytoday.com
